import requests
requests.post('http://localhost:5000/nodes/register', json= {"nodes" :["http://127.0.0.1:5001","http://127.0.0.1:5002"]} )
requests.post('http://localhost:5001/nodes/register', json= {"nodes" :["http://127.0.0.1:5002","http://127.0.0.1:5000"]} )
requests.post('http://localhost:5002/nodes/register', json= {"nodes" :["http://127.0.0.1:5000","http://127.0.0.1:5001"]} )
for i in range(0,5):
    requests.post('http://localhost:5000/transactions/new', json= {"sender": "jintu","recipient": "jeenu","amount": 500} )
    requests.post('http://localhost:5001/transactions/new', json= {"sender": "jintu","recipient": "jeenu","amount": 500} )
    requests.post('http://localhost:5000/mine',json={"secret_key":"1st243juncojqyg3r89by3895"})
    requests.get('http://localhost:5000/nodes/resolve')
    requests.get('http://localhost:5001/nodes/resolve')
    requests.get('http://localhost:5002/nodes/resolve')
    requests.post('http://localhost:5000/transactions/new', json= {"sender": "jintu","recipient": "jeenu","amount": 500} )
    requests.post('http://localhost:5001/transactions/new', json= {"sender": "jintu","recipient": "jeenu","amount": 500} )
    requests.post('http://localhost:5001/mine',json={"secret_key":"2ndfionasio234iokdfoir"})
    requests.get('http://localhost:5000/nodes/resolve')
    requests.get('http://localhost:5001/nodes/resolve')
    requests.get('http://localhost:5002/nodes/resolve')
for i in range(0,1):
    requests.post('http://localhost:5000/transactions/new', json= {"sender": "jintu","recipient": "jeenu","amount": 500} )
    requests.post('http://localhost:5001/transactions/new', json= {"sender": "jintu","recipient": "jeenu","amount": 500} )
    requests.post('http://localhost:5000/mine',json={"secret_key":"1st243juncojqyg3r89by3895"})
    requests.get('http://localhost:5000/nodes/resolve')
    requests.get('http://localhost:5001/nodes/resolve')
    requests.post('http://localhost:5000/transactions/new', json= {"sender": "jintu","recipient": "jeenu","amount": 500} )
    requests.post('http://localhost:5001/transactions/new', json= {"sender": "jintu","recipient": "jeenu","amount": 500} )
    requests.post('http://localhost:5001/mine',json={"secret_key":"2ndfionasio234iokdfoir"})
    requests.get('http://localhost:5000/nodes/resolve')
    requests.get('http://localhost:5001/nodes/resolve')
for i in range(0,3):
    requests.post('http://localhost:5002/transactions/new', json= {"sender": "iadghj","recipient": "kjadgf","amount": 300} )
    requests.post('http://localhost:5002/mine',json={"secret_key":"3rdadnfgklndgpajglfkmn"})
requests.get('http://localhost:5000/nodes/resolve')
requests.get('http://localhost:5001/nodes/resolve')
requests.get('http://localhost:5002/nodes/resolve')